# LUKSO config

# Extends the mainnet preset
PRESET_BASE: 'mainnet'

# Free-form short name of the network that this configuration applies to
CONFIG_NAME: 'lukso'

# Genesis
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 4096
MIN_GENESIS_TIME: 1684856400
GENESIS_DELAY: 2400

# Transition
TERMINAL_TOTAL_DIFFICULTY: 0
TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 1

# Deposit contract
DEPOSIT_CHAIN_ID: 42
DEPOSIT_NETWORK_ID: 42
DEPOSIT_CONTRACT_ADDRESS: 0xcafe00000000000000000000000000000000cafe

# Forks
GENESIS_FORK_VERSION: 0x42000001
ALTAIR_FORK_VERSION: 0x42000002
ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x42000003
BELLATRIX_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x42000004
CAPELLA_FORK_EPOCH: 8100
DENEB_FORK_VERSION: 0x42000005
DENEB_FORK_EPOCH: 123075
ELECTRA_FORK_VERSION: 0x42000006
ELECTRA_FORK_EPOCH: 190800
FULU_FORK_VERSION: 0x42000007
FULU_FORK_EPOCH: 18446744073709551615

# Fork choice
PROPOSER_SCORE_BOOST: 40

# Time parameters
SECONDS_PER_SLOT: 12
SLOTS_PER_EPOCH: 32
SECONDS_PER_ETH1_BLOCK: 12
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
SHARD_COMMITTEE_PERIOD: 256
ETH1_FOLLOW_DISTANCE: 2048

# Sync committee
SYNC_COMMITTEE_SIZE: 512
EPOCHS_PER_SYNC_COMMITTEE_PERIOD: 256

# Validator cycle
INACTIVITY_SCORE_BIAS: 4
INACTIVITY_SCORE_RECOVERY_RATE: 16
MIN_PER_EPOCH_CHURN_LIMIT: 4
CHURN_LIMIT_QUOTIENT: 65536

# Validator Stakes
MAX_EFFECTIVE_BALANCE: 32000000000
MAX_EFFECTIVE_BALANCE_ELECTRA: 2048000000000
EJECTION_BALANCE: 16000000000
